### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "test1@example.com",
  "username": "testuser1",
  "password": "password123",
  "birthDate": "2000-01-01"
}

### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}