spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true   # H2 콘솔 사용
      path: /h2-console

  security:
    oauth2:
      client:
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: email
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            provider: spotify
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/spotify"
            scope: user-read-email

  logging:
    level:
      org.springframework.security: DEBUG

frontend:
  url: http://localhost:3000

jwt:
  secret: FFB2FC7345FB1F68575CDECE5F642ABC1234567890ABCDEF1234567890ABCDEF
  expiration: 86400000
  refresh-expiration: 604800000

server:
  port: 8080